#!/bin/bash

color() {
	if [ "$1" == "red" ]
	then
		echo -e "\e[31m$2\e[0m"
	fi

	if [ "$1" == "green" ]
	then
		echo -e "\e[92m$2\e[0m"
	fi

	if [ "$1" == "touchui" ]
	then
		echo -e "\e[40m\e[36m$2\e[0m"
	fi
}
