#!/bin/bash

successfull () {
	if [ $1 -eq 0 ]
	then
		echo -e " - \e[92msuccess\e[0m"
	else
		echo -e " - \e[31mfailed\e[0m"
		exit 1
	fi
}

parse_yaml() {
	local prefix=$2
	local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
	sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
		-e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
	awk -F$fs '{
		indent = length($1)/2;
		vname[indent] = $2;
		for (i in vname) {if (i > indent) {delete vname[i]}}
		if (length($3) > 0) {
			vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
			printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
		}
	}'
}

check_package() {
	local check=$(dpkg -s $1 2>&1 | grep "install ok")
	if [ -z "$check" ]
	then
		echo "0"
	else
		echo "1"
	fi
}
