#!/bin/bash
BROWSER=""
FORCE=""
XORG_DIR=""
OCTOPRINT_CONFIG=""

HELP="Usage: install [options]

Valid options:
  General options:
    -h, --help               : display this usage information
    -f, --force              : disable exit when a command fails and continue the next step
    -b, --browser <value>    : overwrite which browser needs to be installed
    -x, --xorg <value>       : overwrite folder of xserver to search for existing config files
    -o, --octoprint <value>  : overwrite folder of xserver to search for existing config files
"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-f|--force)
		FORCE=true
		shift # past argument
		;;
		-b|--browser)
		BROWSER="$2"
		shift # past argument
		shift # past value
		;;
		-x|--xorg)
		XORG_DIR="$2"
		shift # past argument
		shift # past value
		;;
		-o|--octoprint)
		OCTOPRINT_CONFIG="$2"
		shift # past argument
		shift # past value
		;;
		-h|--help)
		echo -e "$HELP"
		exit 0
		shift # past argument
		shift # past value
		;;
		*)    # unknown option
		POSITIONAL+=("$1") # save it in an array for later
		shift # past argument
		;;
	esac
done
set -- "${POSITIONAL[@]}"
