#!/bin/bash
DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Default variables
DEBUG=false
BROWSER="chromium-browser"

# Get CLI override (e.g. -browser my-browser or --force)
source $DIR/functions/getopts

# Load local functions
source $DIR/functions/successfull
source $DIR/functions/color

# Enforce this helper to be run as root
if [ $(id -u) -ne 0 ]
then 
	echo -e ""
	echo -e " $(color 'red' 'Run this with \e[1msudo\e[0m\e[31m or as an \e[1muser root')"
	echo -e " $(color 'red' 'Since we need to install and configure packages')"
	echo -e " $(color 'red' 'sudo IS needed here!')"
	echo -e ""
	exit 1
fi

# Show introduction
echo -e "$(color 'touchui' ' ╔╦╗╔═╗╦ ╦╔═╗╦ ╦╦ ╦╦ ')"
echo -e "$(color 'touchui' '  ║ ║ ║║ ║║  ╠═╣║ ║║ ')"
echo -e "$(color 'touchui' '  ╩ ╚═╝╚═╝╚═╝╩ ╩╚═╝╩ ')"
echo -e "$(color 'touchui' 'Uninstall helper v0.0.1')"
[ $DEBUG == true ] && echo -e "$(color 'touchui' 'DEBUG mode enabled')"

# Stop TouchUI if it's active
runCmd service touchui stop

# Execute steps
source $DIR/uninstall-steps/0-boot-to-command
source $DIR/uninstall-steps/1-apt-get-remove
source $DIR/uninstall-steps/2-remove-startup

# Show success message
echo ""
echo "$(color 'green' 'TouchUI is successfully uninstalled!')"
echo ""
echo "$(color 'red' 'Sad to see you go :(')"
echo ""
echo "$(color 'red' 'If you uninstalled this program because of bugs or annoyances, then please give')"
echo "$(color 'red' 'some feedback! We can improve this in the future.')"
echo ""
