#!/bin/bash
source $DIR/functions/successfull

if [ "$(systemctl get-default)" == "graphical.target" ]
then
	echo ""
	echo "Boot to command line:"
	runCmd raspi-config nonint do_boot_behaviour B1
	successfull $?
fi
