#!/bin/bash
source $DIR/functions/successfull

# Get active framebuffer, assume the highest is active
FB="$(ls /dev/ | grep fb | tail -1)"

echo ""
if [ -n "$FB" ]
then
	HASCONFIG=false
	for file in $XORG_DIR/*
	do
		if [ -n "$(cat $file | grep /dev/$FB)" ]
		then
			HASCONFIG=true
		fi
	done

	if [ $HASCONFIG = false ]
	then
		echo "Creating xserver config file:"
		echo 'Section "Device"'                     >> $XORG_DIR/99-fbdev.conf
		echo '  Identifier "touchscreen"'           >> $XORG_DIR/99-fbdev.conf
		echo '  Driver "fbdev"'                     >> $XORG_DIR/99-fbdev.conf
		echo "  Option \"fbdev\" \"/dev/$FB\""      >> $XORG_DIR/99-fbdev.conf
		echo 'EndSection'                           >> $XORG_DIR/99-fbdev.conf
		successfull $?
	else
		echo "Skipping creation of xserver config file:"
		echo " - /dev/$FB already configured"
	fi
else
	echo "Skipping creation of xserver config file:"
	echo " - FrameBuffer was not detected"
fi
