#!/bin/bash
source $DIR/functions/successfull
source $DIR/functions/check_package

[ $(check_package xinit) == 1 ] && DEPENDENCIES+=("xinit" "" OFF)
[ $(check_package xinput) == 1 ] && DEPENDENCIES+=("xinput" "" OFF)
[ $(check_package xserver-xorg) == 1 ] && DEPENDENCIES+=("xserver-xorg" "" OFF)
[ $(check_package xserver-xorg-video-fbdev) == 1 ] && DEPENDENCIES+=("xserver-xorg-video-fbdev" "" OFF)
[ $(check_package x11-xserver-utils) == 1 ] && DEPENDENCIES+=("x11-xserver-utils" "" OFF)
[ $(check_package matchbox) == 1 ] && DEPENDENCIES+=("matchbox" "" OFF)
[ $(check_package unclutter) == 1 ] && DEPENDENCIES+=("unclutter" "" OFF)
[ $(check_package $BROWSER) == 1 ] && DEPENDENCIES+=("$BROWSER" "" OFF)

if [ ${#DEPENDENCIES[@]} -ne 0 ]
then
	REMOVE=$(whiptail --checklist "Select packages installed by TouchUI that can be safily removed: " \
			20 85 10 "${DEPENDENCIES[@]}" 3>&1 1>&2 2>&3)

	if [ $? = 0 ]
	then
		if [ -n "$REMOVE" ]
		then
			echo ""
			echo "Removing dependencies ($(echo ${REMOVE[@]} | tr -d '"')):"
			runCmd apt-get remove $(echo ${REMOVE[@]} | tr -d '"') --yes
			successfull $?
		fi
	fi
fi