#!/bin/bash
. $DIR/functions
. $DIR/get_can_expanded

# Check if file system is expanded.
if [ "$(get_can_expand)" == 1 ]
then
	echo ""
	echo -e "$(color 'red' 'Expand your file system before running this helper.')"
	echo -e "$(color 'red' 'Run `sudo raspi-config`')"
	do_exit
fi
