#!/bin/bash
. $DIR/functions

OCTOPRINT_CONFIG="/home/pi/.octoprint/config.yaml"
eval $(parse_yaml $OCTOPRINT_CONFIG "octoprint_")
echo ""
if [ -z "$octoprint_accessControl_autologinAs" ]
then
	echo "Setup autoLogin for localhost."
	echo "insert the username that can auto login into OctoPrint."
	echo "(Leave this empty to skip this step)"
	read -p 'Username: ' OCTOPRINT_USER
	NEW="accessControl:\n  autologinLocal: true\n  autologinAs: $OCTOPRINT_USER"

	if [ -n "$OCTOPRINT_USER" ]
	then
		echo ""
		echo "Saving autoLogin to config (~/.octoprint/config.yaml)"

		if [ -n "$(cat $OCTOPRINT_CONFIG | grep accessControl)" ]
		then
			sed -i -e "s/accessControl:/$NEW/g" $OCTOPRINT_CONFIG
			successfull $?
		else
			echo "$NEW" >> $OCTOPRINT_CONFIG
			successfull $?
		fi

		service octoprint restart
	else
		echo ""
		echo "Skipping setup autoLogin for localhost:"
		echo " - Cancelled by user"
	fi
else
	echo "Skipping setup autoLogin for localhost:"
	echo " - Login as '$octoprint_accessControl_autologinAs' already configured"
fi
